create table lmcp_task (
id integer not null primary key,
station_code text not null,
ofd_date text not null,
ead text not null,
current_lmcp integer not null,
current_atrops integer not null,
pdr integer not null,
requested integer not null,
sim_link text not null,
value integer not null,
start_time date,
export_time date,
end_time date,
source text not null,
namespace text not null,
type text not null,
wave_group_name text not null,
ship_option_category text not null,
address_type text not null,
package_type text not null,
cluster text not null,
fulfillment_network_type text not null,
volume_type text not null,
week integer not null,
f text not null,
foreign key(station_code) references station (station_code)
);